#!/usr/bin/env python

import os
import sys

if len(sys.argv) < 2:
    print("Usage: #!/usr/bin/env uvr")
    sys.exit(1)

script = sys.argv[1]
script = os.path.realpath(script)
scriptDir = os.path.dirname(script)

os.execlp('uv', 'uv', 'run', '--project', scriptDir, script, *sys.argv[2:])


